{{- if .Values.istio.enable -}}
{{- $name := .Values.fullName }}
{{- $url := printf "%s.%s.svc.cluster.local" $name .Release.Namespace }}
{{- $port := .Values.service.ports.http }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ $name }}-virtual-service"
spec:
  hosts:
    - {{ $url }}
  {{- if .Values.istio.virtualService.hosts }}
    {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  {{- end}}
  {{- if .Values.istio.virtualService.gateways }}
  gateways:
    {{- toYaml .Values.istio.virtualService.gateways | nindent 4 }}
  {{- end}}
  http:
    - match:
        - uri:
            prefix: {{ .Values.istio.virtualService.http.uri.prefix }}
      rewrite:
        uri: {{ .Values.istio.virtualService.http.rewrite.uri }}
      {{- if (and (hasKey .Values.istio.virtualService "http") (hasKey .Values.istio.virtualService.http "timeout")) }}
      timeout: {{ .Values.istio.virtualService.http.timeout }}
      {{- end }}
      {{- if (and (hasKey .Values.istio.virtualService "http") (hasKey .Values.istio.virtualService.http "retries") (.Values.istio.virtualService.http.retries.enable)) }}
      retries:
        attempts: {{ .Values.istio.virtualService.http.retries.attempts | default 3 }}
        perTryTimeout: {{ .Values.istio.virtualService.http.retries.perTryTimeout | default "2s" }}
        {{- if .Values.istio.virtualService.http.retries.retryOn }}
        retryOn: {{ .Values.istio.virtualService.http.retries.retryOn }}
        {{- end }}
      {{- else if (and (hasKey .Values.istio.virtualService "http") (hasKey .Values.istio.virtualService.http "retries") (not .Values.istio.virtualService.http.retries.enable)) }}
      retries:
        attempts: 0
      {{- end }}
      route:
        {{- range $k, $v := .Values.istio.subsets }}
        - destination:
            host: {{ $url }}
            subset: {{ regexReplaceAll "\\.+" $v.version "-" }}
            port:
              number: {{ $port }}
          weight: {{ $v.weight }}
          {{- if $v.mirror }}
          mirror:
            host: {{ $url }}
            subset: {{ regexReplaceAll "\\.+" $v.mirror.version "-" }}
            mirrorPercentage:
              value: {{ $v.mirror.mirrorPercentage }}
          {{- end }}
        {{- end }}
{{- end }}